---
title: "Shared functions and formatting"
author: "Edward Wallace"
date: '2023-05-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE , warning=FALSE, message=FALSE)
```


```{r load_packages, echo=FALSE}
library(tidyverse) # data wrangling, ggplot, etc.
library(reshape2)  # reshape for plate data
library(cowplot)   # nice plot defaults, plot_grid
library(readxl)    # read excel files
library(extrafont) # specify Arial font
library(here)      # find files with relative paths
library(ggformula) # smooth plots with stat_spline
library(lemon)     # figure formatting, repeat axes on facet plots
```

```{r shared_formatting, echo=FALSE}
theme_set(
  theme_cowplot(font_size = 12, font_family = "Arial",
                rel_large = 1) + 
    theme(strip.background = element_blank(),
          panel.border = 
            element_rect(color = "grey90", 
                         fill = NA, 
                         linetype = 1, 
                         linewidth = 1),
          panel.grid.major.y = 
            element_line(linewidth = 0.5, 
                         colour = "grey90"))
)

```


```{r platereader_functions, echo=FALSE}
read_platereader_csv <- function(file, ...) {
  # read plate reader data in transposed .csv format and convert time to hours, from seconds.
  readr::read_csv(file = file, ...) %>%
    dplyr::mutate(Time = Time/3600)
}

read_platereader_xlsx <- function(file, start_row = 52, end_row = start_row + 98) {
  # read TECAN Infinite Pro plate reader data in raw .xlsx format
  # transpose the data into a tidy tibble format
  # convert time to hours, from seconds
  # 
  # 
  #   start_row: the row that begins "Cycle Nr." Default 52 because that's true for the experimental design we used here
  #   end_row: the last row of data, start_row + 98 for 96-well plate
  #
  
  
  # read rows of excel file from start_row to end_row
  plate_data <- 
    readxl::read_excel(path = file, 
                                   range = readxl::cell_rows(start_row:end_row),
                                   col_names = FALSE)
  
  # select column names from column 1 of input data, cleaned up
  platereader_colnames <- 
    c("CycleNo", "Time", "Temp_C", 
      plate_data[[1]][-(1:3)])

  plate_data %>%
    # remove first column
    dplyr::select(!1) %>%
    # transpose
    t() %>%
    # convert to tibble
    dplyr::as_tibble(.name_repair = "minimal") %>%
    # set column names as above
    magrittr::set_colnames(platereader_colnames) %>%
    # convert time in seconds to time in hours
    dplyr::mutate(Time = Time/3600)
}

# well names for 96-well plate
well_names_96_rowfirst <-
  tidyr::expand_grid(wellrow = LETTERS[1:8], wellcol = 1:12) %>%
  tidyr::unite(well, wellrow, wellcol, sep = "") %>%
  dplyr::pull(well)

well_names_96_colfirst <-
  tidyr::expand_grid(wellcol = 1:12, wellrow = LETTERS[1:8]) %>%
  tidyr::unite(well, wellrow, wellcol, sep = "") %>%
  dplyr::pull(well)
  

read_platereader_xlsx_magellan <- 
  function(file, 
           start_row = 2, 
           end_row = start_row + 97,
           well_names = well_names_96_rowfirst) {
  # read TECAN Sunrise / Magellan plate reader data in raw .xlsx format
  # transpose the data into a tidy tibble format
  # 
  #   start_row: 2 that's true for the experimental design we used here
  #   end_row: the last row of data, start_row + 98 for 96-well plate
  #
  
  # select column names from column 1 of input data, cleaned up
  platereader_colnames <- 
    c("Time", "Temp_C", 
      well_names)
  
  plate_data <- 
    # read rows of excel file from start_row to end_row
    readxl::read_excel(path = file, 
                       range = readxl::cell_rows(start_row:end_row),
                       col_names = FALSE) %>%
    # transpose
    t() %>%
    # convert to tibble
    dplyr::as_tibble(.name_repair = "minimal") %>%
    # set column names as above
    magrittr::set_colnames(platereader_colnames) %>%
    # convert time in seconds to time in hours
    dplyr::mutate(Time = Time %>% 
                    stringr::str_remove("s") %>%
                    as.numeric() %>%
                    magrittr::divide_by(3600),
                  Temp_C = Temp_C %>% 
                    stringr::str_remove(" °C") %>%
                    as.numeric()) %>%
    dplyr::mutate_at(well_names, as.numeric)
  
  plate_data
}

read_platemap_csv <- function(file, strain_df = NULL, ...) {
  platemap <- readr::read_csv(file = file, ...)
  if ( !is.null(strain_df) ) {
    platemap <- platemap %>%
      dplyr::left_join(strain_df, by = "Strain")
  }
  platemap
}

reshape_annotate_raw_od <- 
  function(raw_od, 
           platemap, 
           od.name = "OD595", 
           melt.id = "Time", 
           well.name = "Well") {
    raw_od %>%
      # Tidy the data using the melt function from reshape2
      reshape2::melt(id = melt.id, 
                     variable.name = well.name,
                     value.name =  od.name) %>%
      # Annotate by joining with the platemap
      inner_join(platemap, by = well.name) %>%
      as_tibble()
  }

summarise_od_fixed <- function(annotated_od, od.name = "OD595", ...) {
  # summarise OD fixed value across many times
  # here use `...` input to pass conditions to filter
  # e.g. summarise_od_fixed(annotated_od, od.name = "OD595", is.na(Strain))
  annotated_od %>%
    dplyr::filter(...) %>%
    dplyr::summarise(OD_median = median(OD595),
                     OD_mean   = mean(OD595),
                     OD_max    = max(OD595),
                     OD_min    = min(OD595),
                     .groups = "keep")
}

summarise_od_bytime <- function(annotated_od, od.name = "OD595", groups = "Time", ...) {
  # summarise OD at each time
  # here use `...` input to pass conditions to filter
  # e.g. summarise_od_bytime(annotated_od, od.name = "OD595", groups = "Time", is.na(Strain))
  annotated_od %>%
    dplyr::filter(...) %>%
    dplyr::group_by(Time) %>%
    dplyr::summarise(OD_median_time = median(OD595),
                     OD_mean_time   = mean(OD595),
                     OD_max_time    = max(OD595),
                     OD_min_time    = min(OD595),
                     .groups = "keep")
}

normalise_od_2ways <- function(annotatedod, ...) {
  # normalise OD across a plate
  # will NOT work if there are multiple media in a plate; that would require an extra group_by or filtering internally.
  # here use `...` input to pass conditions to filter
  # e.g. normalise_od_2ways(annotated_od, is.na(Strain))
  # e.g. normalise_od_2ways(annotated_od, Well %in% c("A1","A2","A3")) 
  
  normvalues_fixed <- 
    summarise_od_fixed(annotatedod, od.name = "OD595", ...)
  normvalues_bytime <- 
    summarise_od_bytime(annotatedod, od.name = "OD595", groups = "Time", ...)
  annotatedod %>%
    mutate(OD_corrected_fixed = OD595 - normvalues_fixed$OD_median) %>%
    left_join(normvalues_bytime, by = "Time") %>% 
    mutate(OD_corrected_time = OD595 - OD_median_time) 
}

load_annotate_platereader <- 
  function(file_raw_od, 
           file_platemap, 
           datasubdir = "data",
           strain_df = NULL,
           raw_od_start_row = 52) {
    # mini pipeline: loads, annotates, reshapes, plate reader data
    # 
    raw_od <-
      here::here(datasubdir, file_raw_od) %>%
      read_platereader_xlsx(start_row = raw_od_start_row)
    
    platemap <- 
      here::here(datasubdir, file_platemap) %>%
      read_platemap_csv(strain_df = strain_df)
    
    reshape_annotate_raw_od(raw_od = raw_od, 
                            platemap = platemap)
  }
```

```{r growthcurve_plotfunctions, echo = FALSE}
scale_time_hrs <- function(name = "Time (hours)", 
                           breaks = c(0, 12, 24, 48, 72),
                           limits = c(0, 72),
                           expand = c(0, 0),
                           ...) {
  # time in hours with defaults for plate reader growth curves
  scale_x_continuous(name = name, 
                     breaks = breaks,
                     limits = limits,
                     expand = expand,
                     ...)
}

scale_color_strain <- function(strain_df, ...) {
  scale_color_manual(name = "Strain",
                     breaks = strain_df$Strain_nice,
                     values = strain_df$colour,
                     ...)
}

ggplot_growthcurve <- 
  function(data_od,
           value_od = "OD595",
           limits_time = c(0, 72), 
           breaks_time = c(0, 12, 24, 48, 72),
           limits_od = c(0, 0.1),
           breaks_od = c(0, 0.05, 0.1)) {
    # basic plot defaults for growth curve 
    # e.g. 
    ggplot(data = data_od, 
           aes(x = Time, 
               y = .data[[value_od]])) + 
      scale_time_hrs(limits = limits_time,
                     breaks = breaks_time) + 
      scale_y_continuous(name = "OD595",
                         limits = limits_od,
                         expand = c(0, 0),
                         breaks = breaks_od)
  }

ggplot_growthcurve_summary <- function(...) {
  ggplot_growthcurve(...) + 
  geom_line(aes(group = Well, color = Strain_nice), 
            linewidth = 0.2, alpha = 0.2) + 
  stat_summary(aes(color = Strain_nice), 
               fun = "median", geom = "line", linewidth = 1)
}

ggplot_growthcurve_spline <- function(...) {
  ggplot_growthcurve(...) + 
  ggformula::stat_spline(aes(color = Strain_nice),
                         linewidth = 1) 
}

ggplot_growthcurve_spline_pluswells <- function(...) {
  ggplot_growthcurve(...) + 
  geom_line(aes(group = Well, color = Strain_nice), 
            linewidth = 0.2, alpha = 0.2) + 
  ggformula::stat_spline(aes(color = Strain_nice),
                         linewidth = 1) 
}
```
